# Generated by Django 4.1.2 on 2022-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('blurb', models.TextField()),
                ('genre', models.CharField(choices=[(None, ''), ('HOR', 'Horror'), ('DOC', 'Documentary'), ('COM', 'Comedy')], default=None, max_length=3)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
